<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectDataSeeder extends Seeder
{
    public function run(): void
    {
        Project::truncate();

        $projects = [
            // ── Hafriyat ──────────────────────────────────────────────
            [
                'title'       => 'Hafriyat ve Temel Kazı',
                'slug'        => 'hafriyat-ve-temel-kazi',
                'category'    => 'Hafriyat',
                'location'    => 'Ankara',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-01.webp',
                'excerpt'     => 'Konut ve sanayi projelerine yönelik GPS destekli büyük ölçekli temel kazısı ve hafriyat çalışması.',
                'content'     => 'GPS destekli iş makinelerimizle konut ve sanayi alanında büyük ölçekli temel kazısı ve hafriyat operasyonları yürüttük. Modern ekskavatör filomuz ve deneyimli operatör kadromuzla belirlenen takvim ve teknik şartnamelere eksiksiz uyum sağlandı.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 1,
            ],
            [
                'title'       => 'Altyapı Zemin Hazırlığı',
                'slug'        => 'altyapi-zemin-hazirligi',
                'category'    => 'Hafriyat',
                'location'    => 'İstanbul',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-04.webp',
                'excerpt'     => 'Büyük ölçekli altyapı projesi için geniş saha zemin hazırlığı ve kütlesel kazı operasyonu.',
                'content'     => 'İstanbul metropoliten alanında altyapı tesisi yapılacak geniş saha için kapsamlı zemin hazırlığı ve kütlesel kazı operasyonu gerçekleştirildi. Sıkıştırma ve zemin iyileştirme çalışmaları da kapsam dahilinde yürütüldü.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 4,
            ],
            [
                'title'       => 'Derin Temel Kazısı',
                'slug'        => 'derin-temel-kazisi',
                'category'    => 'Hafriyat',
                'location'    => 'Ankara',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-09.webp',
                'excerpt'     => 'Kentsel dönüşüm kapsamında 15 katlı konut bloğu için derin temel kazısı ve moloz uzaklaştırma.',
                'content'     => 'Kentsel dönüşüm projesinde 15 katlı konut bloğu için iktisat sahası kazısı, iksa uygulaması ve yüksek hacimli moloz nakliyesi işlemleri eksiksiz tamamlandı.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 9,
            ],
            [
                'title'       => 'Ankara–Konya Yol Projesi',
                'slug'        => 'ankara-konya-yol-projesi',
                'category'    => 'Hafriyat',
                'location'    => 'Ankara / Konya',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-03.webp',
                'excerpt'     => 'Ankara–Konya karayolu güzergahında büyük ölçekli yol hafriyatı ve zemin tesviyesi.',
                'content'     => 'Ankara–Konya devlet yolu güzergâhında gerçekleştirilen yol hafriyatı projesinde milyonlarca metreküp toprak taşındı. GPS destekli iş makineleri ve geniş araç filosuyla belirlenen süre içinde başarıyla tamamlandı.',
                'is_featured' => false,
                'is_active'   => true,
                'order'       => 3,
            ],
            [
                'title'       => 'Kuzey Ankara Tünel Kazısı',
                'slug'        => 'kuzey-ankara-tunel-kazisi',
                'category'    => 'Hafriyat',
                'location'    => 'Ankara',
                'year'        => '2022',
                'cover_image' => 'assets/img/projects/real-project-05.webp',
                'excerpt'     => 'Kuzey Ankara çevre yolu tünel inşaatı kapsamında gerçekleştirilen derin kaya kazısı.',
                'content'     => 'Kuzey Ankara çevre yolu güzergâhında tünel inşaatına yönelik derin kaya kazısı ve moloz uzaklaştırma operasyonları lisanslı ekipmanlarla yürütüldü.',
                'is_featured' => false,
                'is_active'   => true,
                'order'       => 5,
            ],
            // ── Nakliye ──────────────────────────────────────────────
            [
                'title'       => 'Toprak Taşıma Operasyonu',
                'slug'        => 'toprak-tasima-operasyonu',
                'category'    => 'Nakliye',
                'location'    => 'Ankara',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-02.webp',
                'excerpt'     => 'Büyük çaplı konut projesi için 500.000 m³ hafriyat toprağının taşınması ve depolanması.',
                'content'     => 'Geniş kamyon filomuzla 500.000 m³ hafriyat toprağı belirlenen depolama sahalarına güvenli ve zamanında taşındı. Araç takip sistemleri ve saha koordinasyonu eksiksiz yürütüldü.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 2,
            ],
            [
                'title'       => 'Araç Filosu Sahada',
                'slug'        => 'arac-filosu-sahada',
                'category'    => 'Nakliye',
                'location'    => 'İstanbul',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-08.webp',
                'excerpt'     => 'OSB inşaatı için 30 araçlık damperli kamyon filosuyla yoğun nakliye operasyonu.',
                'content'     => 'Organize Sanayi Bölgesi altyapı inşaatı kapsamında 30 araçlık filosumuz günlük 3 vardiya çalışarak moloz ve toprak nakliyesini tamamladı.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 8,
            ],
            [
                'title'       => 'Yük Taşıma ve Lojistik',
                'slug'        => 'yuk-tasima-ve-lojistik',
                'category'    => 'Nakliye',
                'location'    => 'Sakarya',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-15.webp',
                'excerpt'     => 'Sakarya yol projesi için ağır yük ve yapı malzemesi lojistik hizmetleri.',
                'content'     => 'Sakarya devlet yolu yenileme projesi kapsamında ağır yük ve yapı malzemesi taşımacılığı gerçekleştirildi. Çevre mevzuatına tam uyumlu taşıma operasyonu.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 15,
            ],
            // ── Altyapı ──────────────────────────────────────────────
            [
                'title'       => 'Açık Saha Kazı Çalışması',
                'slug'        => 'acik-saha-kazi-calismasi',
                'category'    => 'Altyapı',
                'location'    => 'Kocaeli',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-24.webp',
                'excerpt'     => 'Sanayi tesisi altyapısı için geniş açık saha kazısı ve zemin iyileştirme.',
                'content'     => 'Kocaeli Sanayi Bölgesi\'nde tesis yapılacak alanda geniş açık saha kazısı, zemin stabilizasyonu ve altyapı hattı tesisi çalışmaları yürütüldü.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 24,
            ],
            [
                'title'       => 'OSB Altyapı ve Kanalizasyon',
                'slug'        => 'osb-altyapi-ve-kanalizasyon',
                'category'    => 'Altyapı',
                'location'    => 'Ankara',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-16.webp',
                'excerpt'     => 'Organize Sanayi Bölgesi için kanalizasyon, yağmursuyu ve içme suyu altyapısı.',
                'content'     => 'OSB kapsamında kanalizasyon, yağmursuyu ve içme suyu hatları toplamda 15 km uzunluğunda döşendi. Tüm kamu mevzuatına uygun biçimde tamamlandı.',
                'is_featured' => false,
                'is_active'   => true,
                'order'       => 16,
            ],
            [
                'title'       => 'İş Makinesi Operasyonu',
                'slug'        => 'is-makinesi-operasyonu',
                'category'    => 'Altyapı',
                'location'    => 'Bursa',
                'year'        => '2022',
                'cover_image' => 'assets/img/projects/real-project-35.webp',
                'excerpt'     => 'Bursa altyapı projelerinde ağır iş makinesi filosu ile kazı ve tesviye.',
                'content'     => 'Bursa ilinde yürütülen birden fazla altyapı projesinde ekskavatör, yükleyici ve dozer filosumuzla kazı ve tesviye hizmetleri verildi.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 35,
            ],
            // ── Arazi Düzenleme ──────────────────────────────────────
            [
                'title'       => 'Arazi Düzenleme',
                'slug'        => 'arazi-duzenleme-projesi',
                'category'    => 'Arazi Düzenleme',
                'location'    => 'Kırşehir',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-31.webp',
                'excerpt'     => 'Hirfanlı barajı çevresinde 120 dönümlük arazinin tesviyesi ve dolgu işleri.',
                'content'     => 'Hirfanlı Barajı çevresinde 120 dönümlük alanda arazi tesviyesi, toprak dolgusu ve kompaksiyon çalışmaları gerçekleştirildi. Zemin raporuna uygun stabilizasyon uygulandı.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 31,
            ],
            // ── Yıkım ────────────────────────────────────────────────
            [
                'title'       => 'Sincan Sanayi Tesisi Yıkımı',
                'slug'        => 'sincan-sanayi-tesisi-yikimi',
                'category'    => 'Yıkım',
                'location'    => 'Ankara',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-27.webp',
                'excerpt'     => 'Sincan OSB\'de atıl durumdaki sanayi tesisinin mekanik yöntemle kontrollü yıkımı.',
                'content'     => 'Sincan Organize Sanayi Bölgesi\'nde atıl durumdaki 3.500 m² kapalı alan tesisi İSG protokollerine uygun biçimde mekanik olarak yıkıldı. Atıklar ayrıştırılarak uygun depolara taşındı.',
                'is_featured' => false,
                'is_active'   => true,
                'order'       => 27,
            ],
            [
                'title'       => 'Kentsel Dönüşüm Yıkımı',
                'slug'        => 'kentsel-donusum-yikimi',
                'category'    => 'Yıkım',
                'location'    => 'İstanbul',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-06.webp',
                'excerpt'     => 'Kentsel dönüşüm kapsamında riskli yapı tespiti yapılan 7 binalık bloğun yıkımı.',
                'content'     => 'İstanbul kentsel dönüşüm projesi kapsamında riskli yapı belgesi olan 7 binadan oluşan bir bloğun kontrollü yıkımı gerçekleştirildi. Komşu binalara zarar verilmeden hassas mekanik yıkım uygulandı.',
                'is_featured' => false,
                'is_active'   => true,
                'order'       => 6,
            ],
            // ── Konut ────────────────────────────────────────────────
            [
                'title'       => 'Mihra Konakları – Ön Cephe',
                'slug'        => 'mihra-konaklari-on-cephe',
                'category'    => 'Konut',
                'location'    => 'Ankara',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-41.webp',
                'excerpt'     => 'Karaçavuş Proje Geliştirme imzasıyla inşa edilen Mihra Konakları konut projesi ön cephe çalışmaları.',
                'content'     => 'Ankara\'da Karaçavuş Proje Geliştirme bünyesinde hayata geçirilen Mihra Konakları projesinin ön cephe kaplama, peyzaj ve dış mekan düzenleme çalışmaları tamamlandı.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 41,
            ],
            [
                'title'       => 'Mihra Konakları – Peyzaj',
                'slug'        => 'mihra-konaklari-peyzaj',
                'category'    => 'Konut',
                'location'    => 'Ankara',
                'year'        => '2024',
                'cover_image' => 'assets/img/projects/real-project-44.webp',
                'excerpt'     => 'Mihra Konakları projesi peyzaj ve dış mekan tasarım uygulamaları.',
                'content'     => 'Mihra Konakları konut projesi kapsamında peyzaj tasarımı ve dış mekan düzenlemeleri hayata geçirildi. Yeşil alan, aydınlatma ve yürüyüş yolu uygulamaları tamamlandı.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 44,
            ],
            [
                'title'       => 'Mihra Konakları – Şantiye',
                'slug'        => 'mihra-konaklari-santiye',
                'category'    => 'Konut',
                'location'    => 'Ankara',
                'year'        => '2023',
                'cover_image' => 'assets/img/projects/real-project-50.webp',
                'excerpt'     => 'Mihra Konakları şantiyesinde üstyapı beton imalatı ve kalıp çalışmaları.',
                'content'     => 'Mihra Konakları şantiyesinde kolon, perde ve döşeme betonarme imalatları ile kalıp çalışmaları yürütüldü. Tüm imalatlar proje müteahhidi ve denetim firması gözetiminde gerçekleştirildi.',
                'is_featured' => true,
                'is_active'   => true,
                'order'       => 50,
            ],
        ];

        foreach ($projects as $row) {
            Project::updateOrCreate(['slug' => $row['slug']], $row);
        }
    }
}
