<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceDataSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'slug'        => 'hafriyat-ve-temel-kazi',
                'title'       => 'Hafriyat ve Temel Kazı',
                'icon'        => 'flaticon-002-welding',
                'cover_image' => 'assets/img/projects/real-project-01.webp',
                'sector'      => 'Hafriyat · Kazı · Zemin',
                'company'     => 'Karaçavuş Proje Geliştirme / Asel İnşaat Hafriyat',
                'excerpt'     => 'Konut, sanayi ve altyapı projelerine yönelik her ölçekte toprak kazısı ve hafriyat çalışması.',
                'content'     => 'GPS destekli iş makineleri ve deneyimli operatör kadromuzla konut temel kazısından büyük ölçekli altyapı hafriyatına kadar tüm projelerde milimetrik hassasiyet sağlıyoruz. Modern ekskavatör ve yükleyici filomuz, dar takvimli ve yüksek hacimli kazı projelerinde de kesintisiz hizmet sunar. Her sahada İSG protokolleri eksiksiz uygulanmakta; toz ve gürültü kontrolü standart gereksinimler olarak hayata geçirilmektedir.',
                'features'    => [
                    'Konut ve sanayi temel kazısı',
                    'Yüksek hacimli derin kazı operasyonları',
                    'GPS destekli hassas hafriyat',
                    'Toz ve gürültü kontrol sistemleri',
                    'İSG sertifikalı ekip ve ekipman',
                    'Kısa sürede yüksek hacim kapasitesi',
                ],
                'order'     => 1,
                'is_active' => true,
            ],
            [
                'slug'        => 'toprak-tasima-ve-nakliye',
                'title'       => 'Toprak Taşıma ve Nakliye',
                'icon'        => 'flaticon-006-truck',
                'cover_image' => 'assets/img/projects/real-project-02.webp',
                'sector'      => 'Nakliye · Lojistik · Filo',
                'company'     => 'Asel İnşaat Hafriyat / Nayifoğulları İnşaat',
                'excerpt'     => 'Geniş kamyon ve damperli araç filomuzla hafriyat toprağı ve molozları hızlı, güvenli taşıyoruz.',
                'content'     => 'Tonajı yüksek damperli kamyonlardan oluşan modern filomuzla hafriyat toprağı, moloz ve inşaat malzemesini belirlenen depolama sahalarına zamanında ve güvenli biçimde ulaştırıyoruz. Saha lojistik koordinasyonu, araç takip sistemleri ve deneyimli şoför kadromuz sayesinde büyük hacimli nakliye operasyonlarında aksaklık yaşanmaz.',
                'features'    => [
                    'Yüksek tonajlı damperli kamyon filosu',
                    'GPS araç takip ve saha koordinasyonu',
                    'Hafriyat toprağı ve moloz taşımacılığı',
                    'İnşaat malzemesi lojistiği',
                    'Depolama sahası seçim danışmanlığı',
                    'Çevre mevzuatına uyumlu taşıma',
                ],
                'order'     => 2,
                'is_active' => true,
            ],
            [
                'slug'        => 'altyapi-insaati',
                'title'       => 'Altyapı İnşaatı',
                'icon'        => 'flaticon-010-tank-1',
                'cover_image' => 'assets/img/projects/real-project-24.webp',
                'sector'      => 'Altyapı · Karayolu · Mühendislik',
                'company'     => 'Asel Alt ve Üst Yapı İnşaat Hafriyat',
                'excerpt'     => 'Karayolu, köprü, viyadük ile su ve kanalizasyon altyapısı projelerinde deneyimli ekibimizle hizmetinizdeyiz.',
                'content'     => 'Asel Alt ve Üst Yapı bünyesinde yürütülen altyapı inşaat hizmetlerimiz; karayolu yapımı, köprü ve viyadük inşası, içme suyu ve atıksu hattı tesisi ile doğalgaz boru döşeme çalışmalarını kapsamaktadır. Kamu ihale deneyimimiz ve güçlü ekipman parkımızla büyük ölçekli kentsel altyapı projelerinde güvenilir çözümler üretiyoruz.',
                'features'    => [
                    'Karayolu ve bölünmüş yol yapımı',
                    'Köprü, viyadük ve menfez inşası',
                    'İçme suyu ve kanalizasyon hattı',
                    'Doğalgaz boru döşeme çalışmaları',
                    'Kamu altyapı ihalelerinde deneyim',
                    'Mühendislik ve yapım denetimi',
                ],
                'order'     => 3,
                'is_active' => true,
            ],
            [
                'slug'        => 'ustyapi-ve-yapi-insaati',
                'title'       => 'Üstyapı ve Yapı İnşaatı',
                'icon'        => 'flaticon-004-walkie-talkie',
                'cover_image' => 'assets/img/projects/real-project-41.webp',
                'sector'      => 'İnşaat · Konut · Sanayi',
                'company'     => 'Nayifoğulları İnşaat / Karaçavuş Proje Geliştirme',
                'excerpt'     => 'Konut, sanayi yapıları ve ticari binalar dahil her ölçekteki üstyapı projesini anahtar teslim sunuyoruz.',
                'content'     => 'Nayifoğulları İnşaat ve Karaçavuş Proje Geliştirme iş birliğiyle hayata geçirilen üstyapı projelerimiz; konut siteleri, sanayi tesisleri, depolar ve ticari yapıları kapsamaktadır. Statik hesaptan beton uygulamasına, çatı sisteminden dış cephe işlerine kadar tüm inşaat süreçlerini tek çatı altında yönetiyoruz.',
                'features'    => [
                    'Konut ve site inşaatı',
                    'Sanayi yapıları ve depo inşaatı',
                    'Ticari yapı ve plaza inşaatı',
                    'Anahtar teslim proje yönetimi',
                    'Beton, çelik ve prefabrik yapı',
                    'Tadilat ve güçlendirme çalışmaları',
                ],
                'order'     => 4,
                'is_active' => true,
            ],
            [
                'slug'        => 'kontrollu-yikim',
                'title'       => 'Kontrollü Yıkım',
                'icon'        => 'flaticon-015-cart',
                'cover_image' => 'assets/img/projects/real-project-09.webp',
                'sector'      => 'Yıkım · Kentsel Dönüşüm · İSG',
                'company'     => 'Nayifoğulları YMK Yıkım Adi Ortaklığı',
                'excerpt'     => 'Lisanslı yıkım ekipleriyle bina ve tesis yıkımını güvenli, hızlı ve çevreye duyarlı biçimde gerçekleştiriyoruz.',
                'content'     => 'Nayifoğulları YMK Yıkım Adi Ortaklığı bünyesinde yürütülen kontrollü yıkım hizmetlerimiz; mekanik yıkım, patlayıcılı yıkım ve endüstriyel tesis sökümünü kapsamaktadır. Kentsel dönüşüm projelerinde risk tespitinden yıkım planlamasına, atık ayrıştırmasından moloz nakliyesine kadar tüm süreç İSG standartlarında yönetilmektedir.',
                'features'    => [
                    'Mekanik ve patlayıcılı bina yıkımı',
                    'Kentsel dönüşüm yıkım projeleri',
                    'Endüstriyel tesis ve fabrika sökümü',
                    'Yıkım atığı ayrıştırma ve geri kazanım',
                    'Moloz kaldırma ve saha temizliği',
                    'İSG planlaması ve denetimi',
                ],
                'order'     => 5,
                'is_active' => true,
            ],
            [
                'slug'        => 'arazi-duzenleme',
                'title'       => 'Arazi Düzenleme',
                'icon'        => 'flaticon-048-chemical',
                'cover_image' => 'assets/img/projects/real-project-31.webp',
                'sector'      => 'Zemin · Dolgu · Tesviye',
                'company'     => 'Karaçavuş Proje Geliştirme / Asel İnşaat Hafriyat',
                'excerpt'     => 'Proje alanlarının zemin tesviyesi, dolgu, kompaksiyon ve zemin iyileştirme işlemlerini hassasiyetle yapıyoruz.',
                'content'     => 'İnşaata hazır arazi oluşturmak için gerçekleştirdiğimiz arazi düzenleme hizmetlerimiz; toprak dolgusu, kompaksiyon, zemin stabilizasyonu ve tesviye çalışmalarını kapsamaktadır. Sert ve bataklık zeminlerde zemin iyileştirme yöntemlerini uygulayan ekibimiz, proje alanını belirlenen kot ve eğimlere getirerek inşaat süreçlerini güvence altına alır.',
                'features'    => [
                    'Toprak dolgusu ve kompaksiyon',
                    'Zemin stabilizasyonu ve iyileştirme',
                    'Kot ve eğim tesviyesi',
                    'Drenaj ve yüzey suyu yönetimi',
                    'Bitki örtüsü temizleme ve sıyırma',
                    'Arazi sınırlama ve şev stabilizasyonu',
                ],
                'order'     => 6,
                'is_active' => true,
            ],
            [
                'slug'        => 'proje-gelistirme',
                'title'       => 'Proje Geliştirme',
                'icon'        => 'flaticon-020-planning',
                'cover_image' => 'assets/img/projects/real-project-44.webp',
                'sector'      => 'Planlama · Fizibilite · Yönetim',
                'company'     => 'Karaçavuş Proje Geliştirme',
                'excerpt'     => 'Fizibilite analizinden ihale süreçlerine, proje tasarımından inşaat yönetimine kadar kapsamlı destek.',
                'content'     => 'Karaçavuş Proje Geliştirme bünyesinde sunduğumuz proje geliştirme hizmetleri; arsa değerlendirmesi ve fizibilite analizinden başlayarak mimari ve mühendislik koordinasyonu, ihale süreçleri yönetimi ve inşaat denetimini kapsamaktadır. Yatırımcı, müteahhit ve kamu kurumlarına tek elden danışmanlık ve yüklenicilik desteği sağlıyoruz.',
                'features'    => [
                    'Arsa değerlendirme ve fizibilite',
                    'Mimari ve mühendislik koordinasyonu',
                    'Kamu ve özel ihale süreçleri',
                    'İnşaat yönetimi ve hakediş takibi',
                    'Ruhsat ve izin süreçleri danışmanlığı',
                    'Yatırımcı temsil ve proje kontrol',
                ],
                'order'     => 7,
                'is_active' => true,
            ],
            [
                'slug'        => 'arac-ve-is-makinesi-ticareti',
                'title'       => 'Araç ve İş Makinesi Ticareti',
                'icon'        => 'flaticon-008-machine-1',
                'cover_image' => 'assets/img/projects/real-project-omkar.jpg',
                'sector'      => 'Otomotiv · Ticari Araç · Galeri',
                'company'     => 'Ömkar Otomotiv',
                'excerpt'     => 'Binek araç, hafriyat kamyonu ve iş makinesi alım satımında güvenilir galeri hizmeti sunuyoruz.',
                'content'     => 'Ömkar Otomotiv bünyesinde sunduğumuz araç ticareti hizmetleri; binek otomobil, kamyon, damperli araç ve iş makinesi (ekskavatör, yükleyici, dozer) alım satımını kapsamaktadır. Sahibinden.com üzerinden aktif ilan yönetimiyle hem bireysel hem kurumsal alıcılara ulaşıyor; kurumsal filo yenileme ve ikinci el araç değerleme konularında da danışmanlık sağlıyoruz.',
                'features'    => [
                    'Binek otomobil alım ve satımı',
                    'Hafriyat kamyonu ve damperli araç',
                    'Ekskavatör, yükleyici ve dozer ticareti',
                    'Kurumsal filo yenileme danışmanlığı',
                    'İkinci el araç değerleme ve ekspertiz',
                    'Sahibinden.com aktif ilan yönetimi',
                ],
                'order'     => 8,
                'is_active' => true,
            ],
            [
                'slug'        => 'isg-ve-teknik-danismanlik',
                'title'       => 'İSG ve Teknik Danışmanlık',
                'icon'        => 'flaticon-037-forklift',
                'cover_image' => 'assets/img/service/service-6-m.webp',
                'sector'      => 'İSG · Denetim · Danışmanlık',
                'company'     => 'Karaçavuş Şirketler Grubu',
                'excerpt'     => 'Tüm projelerimizde İSG sertifikalı uzmanlarımızla iş güvenliği planlaması ve teknik denetim hizmeti.',
                'content'     => 'Karaçavuş Şirketler Grubu bünyesindeki tüm şantiye ve operasyonlarda İSG standartları eksiksiz uygulanmaktadır. İSG uzmanı kadromuz; risk değerlendirmesi, güvenlik planı hazırlama, çalışan eğitimi ve periyodik denetim hizmetleri sunmaktadır. Grup dışındaki projelere de teknik danışmanlık ve İSG denetimi yapılmaktadır.',
                'features'    => [
                    'Sahada İSG risk değerlendirmesi',
                    'Güvenlik planı ve acil eylem prosedürleri',
                    'Çalışan İSG eğitimi ve bilinçlendirme',
                    'Periyodik saha denetimi ve raporlama',
                    'Ekipman ve makine güvenlik kontrolü',
                    'Kamu denetimlerine hazırlık desteği',
                ],
                'order'     => 9,
                'is_active' => false,
            ],
        ];

        foreach ($data as $row) {
            Service::where('slug', $row['slug'])->update([
                'title'       => $row['title'],
                'icon'        => $row['icon'],
                'cover_image' => $row['cover_image'],
                'sector'      => $row['sector'],
                'company'     => $row['company'],
                'excerpt'     => $row['excerpt'],
                'content'     => $row['content'],
                'features'    => json_encode($row['features']),
                'order'       => $row['order'],
                'is_active'   => $row['is_active'],
            ]);
        }
    }
}
