<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        // Zaten kayıt varsa çalışma
        if (Vehicle::count() > 0) {
            $this->command->info('Vehicles already seeded, skipping.');
            return;
        }

        $vehicles = [
            [
                'name'           => '2015 Land Rover Range Rover',
                'slug'           => '2015-land-rover-range-rover-omkar-1',
                'brand'          => 'land-rover',
                'year'           => '2015',
                'price'          => null,
                'km'             => null,
                'category'       => 'arazi_suv',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-arazi-suv-pickup-land-rover-omkar-otomotivden-2015-model-range-rover-1235342948/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 1,
            ],
            [
                'name'           => 'Land Rover Range Rover Sport',
                'slug'           => 'land-rover-range-rover-sport-omkar-2',
                'brand'          => 'land-rover',
                'year'           => null,
                'price'          => null,
                'km'             => null,
                'category'       => 'arazi_suv',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-arazi-suv-pickup-land-rover-omkar-otomotivden-range-rover-sport-1235354929/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 2,
            ],
            [
                'name'           => '2021 Hyundai Tucson',
                'slug'           => '2021-hyundai-tucson-omkar-3',
                'brand'          => 'hyundai',
                'year'           => '2021',
                'price'          => null,
                'km'             => null,
                'category'       => 'arazi_suv',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-arazi-suv-pickup-hyundai-omkar-otomotviden-2021-model-tucson-1308567092/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 3,
            ],
            [
                'name'           => '2022 Citroen C5 Aircross',
                'slug'           => '2022-citroen-c5-aircross-omkar-4',
                'brand'          => 'citroen',
                'year'           => '2022',
                'price'          => null,
                'km'             => null,
                'category'       => 'arazi_suv',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-arazi-suv-pickup-citroen-omkar-otomotivden-2022-model-c5-aircross-1308557868/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 4,
            ],
            [
                'name'           => '2024 Volvo S90',
                'slug'           => '2024-volvo-s90-omkar-5',
                'brand'          => 'volvo',
                'year'           => '2024',
                'price'          => null,
                'km'             => null,
                'category'       => 'otomobil',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-otomobil-volvo-omkar-otomotiv-den-2024-model-volvo-s90-1305229359/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 5,
            ],
            [
                'name'           => '2020 Audi A5',
                'slug'           => '2020-audi-a5-omkar-6',
                'brand'          => 'audi',
                'year'           => '2020',
                'price'          => null,
                'km'             => null,
                'category'       => 'otomobil',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-otomobil-audi-omkar-otomotivden-2020-model-audi-a5-1268019712/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 6,
            ],
            [
                'name'           => 'Fiat Minivan & Panelvan',
                'slug'           => 'fiat-minivan-panelvan-omkar-7',
                'brand'          => 'fiat',
                'year'           => null,
                'price'          => null,
                'km'             => null,
                'category'       => 'minivan',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-minivan-panelvan-fiat-omkar-otomotivden-1306813517/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 7,
            ],
            [
                'name'           => '2018 Fiat Doblo',
                'slug'           => '2018-fiat-doblo-omkar-8',
                'brand'          => 'fiat',
                'year'           => '2018',
                'price'          => null,
                'km'             => null,
                'category'       => 'minivan',
                'vehicle_type'   => null,
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-minivan-panelvan-fiat-omkar-otomotivden-2018-model-fiat-doblo-1308572759/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 8,
            ],
            [
                'name'           => '2023 Mercedes Arocs 4148 Kamyon',
                'slug'           => '2023-mercedes-arocs-4148-kamyon-omkar-9',
                'brand'          => 'mercedes',
                'year'           => '2023',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'kamyon',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-kamyon-kamyonet-omkar-otomotivden-2023-model-arocs-4148-1302284525/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 9,
            ],
            [
                'name'           => '2023 Özünlü Dorse',
                'slug'           => '2023-ozunlu-dorse-omkar-10',
                'brand'          => 'ozunlu',
                'year'           => '2023',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'dorse',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-dorse-omkar-otomotivden-2023-ozunlu-dorse-1305235456/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 10,
            ],
            [
                'name'           => '2013 Mercedes Axor 1840 Retardarlı',
                'slug'           => '2013-mercedes-axor-1840-retardarli-omkar-11',
                'brand'          => 'mercedes',
                'year'           => '2013',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-2013-model-retardarli-axor-1840-1299490961/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 11,
            ],
            [
                'name'           => '2021 Mercedes 1848 + 2026 Anıl Dorse Takım',
                'slug'           => '2021-mercedes-1848-2026-anil-dorse-takim-omkar-12',
                'brand'          => 'mercedes',
                'year'           => '2021',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-2021-model-1848-takim-halinde-2026-model-anil-1302287319/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 12,
            ],
            [
                'name'           => '2018 Ford 1842 + 2023 Özünlü Dorse Takım',
                'slug'           => '2018-ford-1842-2023-ozunlu-dorse-takim-omkar-13',
                'brand'          => 'ford',
                'year'           => '2018',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-satilik-takim-2018-1842-ford-2023-ozunlu-dorse-1307298924/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 13,
            ],
            [
                'name'           => '2018 Mercedes 1842',
                'slug'           => '2018-mercedes-1842-omkar-14',
                'brand'          => 'mercedes',
                'year'           => '2018',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-satilik-2018-model-1842-1295854164/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 14,
            ],
            [
                'name'           => '2021 Mercedes Actros 1845',
                'slug'           => '2021-mercedes-actros-1845-omkar-15',
                'brand'          => 'mercedes',
                'year'           => '2021',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-2021-model-actros-1845-1262567369/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 15,
            ],
            [
                'name'           => '2018 Ford 1842',
                'slug'           => '2018-ford-1842-omkar-16',
                'brand'          => 'ford',
                'year'           => '2018',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-satilik-2018-ford-1842-1307294889/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 16,
            ],
            [
                'name'           => '2018 Mercedes Actros 1842',
                'slug'           => '2018-mercedes-actros-1842-omkar-17',
                'brand'          => 'mercedes',
                'year'           => '2018',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-2018-model-actros-1842-1263906336/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 17,
            ],
            [
                'name'           => '2010 Scania G420 + Öztreyler Takım',
                'slug'           => '2010-scania-g420-oztreyler-takim-omkar-18',
                'brand'          => 'scania',
                'year'           => '2010',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-scania-g420-2010-model-oztreyler-takim-fiyati-1297716517/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 18,
            ],
            [
                'name'           => '2021 Mercedes Arocs 4148 Kamyon',
                'slug'           => '2021-mercedes-arocs-4148-kamyon-omkar-19',
                'brand'          => 'mercedes',
                'year'           => '2021',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'kamyon',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-kamyon-kamyonet-omkar-otomotivden-2021-model-arocs-4148-1297841525/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 19,
            ],
            [
                'name'           => '2015 Mercedes G400',
                'slug'           => '2015-mercedes-g400-omkar-20',
                'brand'          => 'mercedes',
                'year'           => '2015',
                'price'          => null,
                'km'             => null,
                'category'       => 'ticari',
                'vehicle_type'   => 'cekici',
                'sahibinden_url' => 'https://www.sahibinden.com/ilan/vasita-ticari-araclar-cekici-omkar-otomotivden-2015-model-g400-1297869329/detay',
                'cover_image'    => null,
                'company'        => 'Ömkar Otomotiv',
                'is_active'      => true,
                'order'          => 20,
            ],
        ];

        foreach ($vehicles as $data) {
            Vehicle::create($data);
        }

        $this->command->info('20 vehicles seeded.');
    }
}
